### ISSUE TITLE
Installer hangs at Choco install

### ISSUE THREAD

**Issue by zhntrinc** [BenHerbst/Dalaix#6]
Installer hangs:

Installing Choco
ReferenceError [Error]: alert is not defined
    at setupEntries (C:\Users\IronMan\AppData\Local\Programs\dalaix\resources\app.asar\out\main\installWorker-acd0c3c3.js:60:7)
    at run (C:\Users\IronMan\AppData\Local\Programs\dalaix\resources\app.asar\out\main\installWorker-acd0c3c3.js:24:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by BenHerbst** [comment]
Hello,
this Error shows that it can't show an error message (alert is not defined, I am going to fix that),
but the Error message is about not being able to create 3 files: autostart.bat, start.bat and stop.bat.
You may somehow run Dalai without permissions for the C:\Dalai folder?
Please try to execute it from an evaluated admin shell, if it still doesn't works, try to create a file in C:\Dalai and tell me if that works.

**Comment by zhntrinc** [comment]
I was already running it from an admin shell. Creating the C:\Dalai folder let it finish the install but it does not seem to be installing the models. I tried with all the different models to the same result.

**Comment by BenHerbst** [comment]
go into C:\Dalai\dalai and type: npm install && npx dalai alpaca install 7B

**Comment by BenHerbst** [comment]
Idk why it failed for you at all, I got it working in VMs and other users had it working too
